services:
  weaviate:
    image: semitechnologies/weaviate:1.24.12
    container_name: diplo-weaviate
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: "20"
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "text2vec-transformers"
      ENABLE_MODULES: "text2vec-transformers,bm25"
      TRANSFORMERS_INFERENCE_API: "http://t2v:8080"
      CLUSTER_HOSTNAME: "node1"
    restart: unless-stopped
    depends_on:
      - t2v

  t2v:
    image: semitechnologies/transformers-inference:sentence-transformers-all-MiniLM-L6-v2
    container_name: diplo-t2v
    environment:
      ENABLE_CUDA: "0"
    restart: unless-stopped

networks:
  default:
    name: diplo-net
